### ISSUE TITLE
krew installation not working on Macos

### ISSUE THREAD

**Issue by jheyduk** [kcl-lang/kubectl-kcl#27]
### 1. Minimal reproduce step (Required)

kubectl krew install kubectl-kcl/kubectl-kcl

### 2. What did you expect to see? (Required)
Installation successful

### 3. What did you see instead (Required)
Updated the local copy of plugin index.
Updated the local copy of plugin index "kubectl-kcl".
Installing plugin: kubectl-kcl
W0415 11:43:01.188678   68348 install.go:164] failed to install plugin "kubectl-kcl": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/kcl-lang/kubectl-kcl/releases/download/v0.5.0/kubectl-kcl-darwin-amd64.tar.gz", status code 404
failed to install some plugins: [kubectl-kcl]: install failed: failed to unpack into staging dir: failed to unpack the plugin archive: failed to obtain plugin archive: failed to download "https://github.com/kcl-lang/kubectl-kcl/releases/download/v0.5.0/kubectl-kcl-darwin-amd64.tar.gz", status code 404

### 4. Solution
The files are named differently. It needs to be kubectl-kcl-macos-amd64.tar.gz in my case.

Please fix it in builds or rename the binaries in krew-index-file. Thanks!

**Comment by Peefy** [comment]
Thank you! I've opened a PR to fix this https://github.com/kcl-lang/kubectl-kcl/pull/28
